### ISSUE TITLE
Player gets thrown into the ocean when deploying

### ISSUE THREAD

**Issue by Psylicium** [mudzereli/DayZEpochDeployableBike#1]
I don't know if I'm doing this right, but I have a slight issue with your deployable bike script. Sometimes, when a player creates a bike near the coast, he suddenly ends up like 5000m out in the ocean. I haven't been told if it happens during the construction phase, or when he tries to ride it.

**Comment by oiad** [comment]
Hi Psylicium, this is an old post but basically what is happening is the player is getting on the deployed bike before it's deployed. To fix this you need to move the distance back from the player of the deployable. I.e:
`["ItemToolbox",[0,8,2],5,0.9,true,false,false,false,false,true,true,["MMT_Civ"],[],["ItemToolbox"],"true"],`
